#!/usr/bin/env bash
# Interactively assemble ansible/vault-chat.yml — the encrypted secrets for the
# chat profile: the GHCR read:packages token, the R2 object-store API credentials,
# and the chat plane's OWN secrets (chat_vc_issuer_seed + chat_bot_claim_secret).
# NATS is mesh mTLS (a client cert, no password), so there's no NATS secret here.
# It lives OUTSIDE group_vars so molecule/CI never auto-load it; apply.sh loads it.
#
# Unlike the account script this does NOT generate keypairs — the cross-plane
# PUBLIC halves (chat_voucher_pubkey, chat_anon_issuer_pub) come FROM the account
# host (its set-account-secrets.sh printed them) and are pasted into
# group_vars/chat.yml (public config, not the vault).
#
# Run on a TRUSTED machine. Secrets are typed hidden or generated locally; nothing
# is echoed. The file is ansible-vault ENCRYPTED before it rests in git.
# Needs: openssl, ansible-vault, python3.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VAULT="$ROOT/ansible/vault-chat.yml"

for bin in openssl ansible-vault python3; do
  command -v "$bin" >/dev/null 2>&1 || { echo "$bin is required." >&2; exit 1; }
done

if [ -e "$VAULT" ]; then
  read -rp "vault-chat.yml already exists — overwrite? [y/N] " ans
  [ "$ans" = y ] || { echo "Aborted."; exit 1; }
fi

# Secrets already exported in the environment (e.g. `source ~/.bashrc`) are
# picked up silently; anything not in the env is prompted for with hidden input.
env_or_prompt() {  # <varname-to-set> <env-var> <prompt>
  local cur="${!2:-}"
  if [ -n "$cur" ]; then printf -v "$1" '%s' "$cur";
  else read -rsp "$3" "$1"; echo; fi
}

# --- 1. GHCR token (read:packages) --------------------------------------------
env_or_prompt GHCR_TOKEN CHAT_GHCR_TOKEN "GHCR read:packages token (github PAT, hidden): "
[ -n "$GHCR_TOKEN" ] || { echo "Empty token — aborting." >&2; exit 1; }

# --- 2. R2 / object-store credentials (from CHAT_R2_* env, else prompt) --------
env_or_prompt R2_KEY_ID CHAT_R2_ACCESS_KEY_ID   "R2 access key id (hidden): "
env_or_prompt R2_SECRET CHAT_R2_SECRET_ACCESS_KEY "R2 secret access key (hidden): "
# Optional image-scanner API key — only vaulted if present (env or prompt-empty).
MOD_KEY="${CHAT_MODERATION_API_KEY:-}"

# --- 3. chat plane's own secrets (generate if blank) --------------------------
read -rsp "chat_vc_issuer_seed (64 hex) — ENTER to generate: " VC_SEED; echo
[ -n "$VC_SEED" ] || VC_SEED="$(openssl rand -hex 32)"
read -rsp "chat_bot_claim_secret — ENTER to generate: " BOT_SECRET; echo
[ -n "$BOT_SECRET" ] || BOT_SECRET="$(openssl rand -hex 24)"

# --- write plaintext, then encrypt in place -----------------------------------
umask 077
{
  echo "---"
  echo "# Generated by set-chat-secrets.sh — ansible-vault encrypted."
  echo "chat_ghcr_token: \"$GHCR_TOKEN\""
  echo "chat_r2_access_key_id: \"$R2_KEY_ID\""
  echo "chat_r2_secret_access_key: \"$R2_SECRET\""
  echo "chat_vc_issuer_seed: \"$VC_SEED\""
  echo "chat_bot_claim_secret: \"$BOT_SECRET\""
  [ -n "$MOD_KEY" ] && echo "chat_moderation_api_key: \"$MOD_KEY\""
} > "$VAULT"
unset GHCR_TOKEN R2_KEY_ID R2_SECRET VC_SEED BOT_SECRET MOD_KEY

echo
echo "Encrypting $VAULT — you'll be prompted for a vault password"
echo "(remember it; the same one is needed at apply time via ANSIBLE_VAULT_PASSWORD_FILE)."
ansible-vault encrypt "$VAULT"
git -C "$ROOT" add -f "$VAULT"

# Only nag about the public halves if group_vars doesn't already have them.
GV="$ROOT/ansible/group_vars/chat.yml"
if grep -qE '^chat_voucher_pubkey:[[:space:]]*"[0-9a-f]{64}"' "$GV" 2>/dev/null; then
  HALVES="── group_vars/chat.yml already has the cross-plane public halves ✓ ──"
else
  HALVES=$'── Still needed in group_vars/chat.yml (PUBLIC, from the ACCOUNT host) ──\nPaste what the account host'"'"'s set-account-secrets.sh printed:\n    chat_voucher_pubkey:  <CHAT_VOUCHER_PUBKEY>\n    chat_anon_issuer_pub: <the anon-issuer PUBLIC PEM>'
fi

cat <<EOF

── vault-chat.yml written, encrypted, and git-staged (add -f) ──────────────────
Commit + push it (it is ciphertext, safe on the remotes):
    git -C "$ROOT" commit -m "chat: add encrypted vault" && git -C "$ROOT" push

$HALVES
NOTE: the generated chat_bot_claim_secret is now the source of truth — configure
the bot process with the SAME value (view it later: ansible-vault view $VAULT).
EOF
