#!/usr/bin/env bash
# Interactively assemble ansible/vault-chat.yml — the encrypted secrets for the
# chat profile: the GHCR read:packages token, the R2 object-store API credentials,
# and the chat plane's OWN secrets (chat_vc_issuer_seed + chat_bot_claim_secret).
# NATS is mesh mTLS (a client cert, no password), so there's no NATS secret here.
# It lives OUTSIDE group_vars so molecule/CI never auto-load it; apply.sh loads it.
#
# Unlike the account script this does NOT generate keypairs — the cross-plane
# PUBLIC halves (chat_voucher_pubkey, chat_anon_issuer_pub) come FROM the account
# host (its set-account-secrets.sh printed them) and are pasted into
# group_vars/chat.yml (public config, not the vault).
#
# Run on a TRUSTED machine. Secrets are typed hidden or generated locally; nothing
# is echoed. The file is ansible-vault ENCRYPTED before it rests in git.
# Needs: openssl, ansible-vault, python3.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VAULT="$ROOT/ansible/vault-chat.yml"

for bin in openssl ansible-vault python3; do
  command -v "$bin" >/dev/null 2>&1 || { echo "$bin is required." >&2; exit 1; }
done

if [ -e "$VAULT" ]; then
  read -rp "vault-chat.yml already exists — overwrite? [y/N] " ans
  [ "$ans" = y ] || { echo "Aborted."; exit 1; }
fi

# --- 1. GHCR token (read:packages) --------------------------------------------
read -rsp "GHCR read:packages token (github PAT, hidden): " GHCR_TOKEN; echo
[ -n "$GHCR_TOKEN" ] || { echo "Empty token — aborting." >&2; exit 1; }

# --- 2. R2 / object-store credentials -----------------------------------------
read -rsp "R2 access key id (hidden): " R2_KEY_ID; echo
read -rsp "R2 secret access key (hidden): " R2_SECRET; echo

# --- 3. chat plane's own secrets (generate if blank) --------------------------
read -rsp "chat_vc_issuer_seed (64 hex) — ENTER to generate: " VC_SEED; echo
[ -n "$VC_SEED" ] || VC_SEED="$(openssl rand -hex 32)"
read -rsp "chat_bot_claim_secret — ENTER to generate: " BOT_SECRET; echo
[ -n "$BOT_SECRET" ] || BOT_SECRET="$(openssl rand -hex 24)"

# --- write plaintext, then encrypt in place -----------------------------------
umask 077
{
  echo "---"
  echo "# Generated by set-chat-secrets.sh — ansible-vault encrypted."
  echo "chat_ghcr_token: \"$GHCR_TOKEN\""
  echo "chat_r2_access_key_id: \"$R2_KEY_ID\""
  echo "chat_r2_secret_access_key: \"$R2_SECRET\""
  echo "chat_vc_issuer_seed: \"$VC_SEED\""
  echo "chat_bot_claim_secret: \"$BOT_SECRET\""
} > "$VAULT"
unset GHCR_TOKEN R2_KEY_ID R2_SECRET VC_SEED BOT_SECRET

echo
echo "Encrypting $VAULT — you'll be prompted for a vault password"
echo "(remember it; the same one is needed at apply time via ANSIBLE_VAULT_PASSWORD_FILE)."
ansible-vault encrypt "$VAULT"
git -C "$ROOT" add -f "$VAULT"

cat <<EOF

── vault-chat.yml written, encrypted, and git-staged (add -f) ──────────────────
Commit + push it (it is ciphertext, safe on the remotes):
    git -C "$ROOT" commit -m "chat: add encrypted vault" && git -C "$ROOT" push

── Still needed in group_vars/chat.yml (PUBLIC config, from the ACCOUNT host) ──
Paste the values the account host's set-account-secrets.sh printed:
    chat_voucher_pubkey:  <CHAT_VOUCHER_PUBKEY>
    chat_anon_issuer_pub: <the anon-issuer PUBLIC PEM>
Also confirm chat_bot_claim_secret matches the bot process (and the account host).
EOF
