#!/usr/bin/env bash
# Assemble ansible/vault-seed.yml — the encrypted secrets for the seed profile.
# Pulls the GHCR token AND the bot-claim secret FROM vault-chat.yml so
# seed_chat_bot_claim_secret CANNOT drift from the chat plane's (a mismatch →
# seeded bots/harold can't claim). The only NEW value is seed_pw (the demo
# tester/crowd login password). One vault password (the one all your vaults use)
# reads vault-chat and encrypts vault-seed.
#
# Needs: ansible-vault, python3, openssl. Run on a TRUSTED machine.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VAULT="$ROOT/ansible/vault-seed.yml"
CHAT="$ROOT/ansible/vault-chat.yml"

for bin in ansible-vault python3 openssl; do
  command -v "$bin" >/dev/null 2>&1 || { echo "$bin is required." >&2; exit 1; }
done
[ -f "$CHAT" ] || { echo "ansible/vault-chat.yml not found — set up the chat vault first." >&2; exit 1; }
if [ -e "$VAULT" ]; then
  read -rp "vault-seed.yml already exists — overwrite? [y/N] " ans
  [ "$ans" = y ] || { echo "Aborted."; exit 1; }
fi

# One vault password for both the read (vault-chat) and the write (vault-seed).
read -rsp "Vault password (the one your other vaults use): " VP; echo
[ -n "$VP" ] || { echo "Empty password — aborting." >&2; exit 1; }
PWF="$(mktemp)"; trap 'rm -f "$PWF"' EXIT; printf '%s' "$VP" > "$PWF"; unset VP

# Reuse the GHCR token + bot-claim from the chat vault (guarantees the match).
eval "$(ansible-vault view --vault-password-file "$PWF" "$CHAT" | python3 -c '
import sys, yaml, shlex
d = yaml.safe_load(sys.stdin) or {}
print("GH=" + shlex.quote(d.get("chat_ghcr_token", "")))
print("BC=" + shlex.quote(d.get("chat_bot_claim_secret", "")))
')"
[ -n "${GH:-}" ] || { echo "vault-chat.yml has no chat_ghcr_token." >&2; exit 1; }
[ -n "${BC:-}" ] || { echo "vault-chat.yml has no chat_bot_claim_secret." >&2; exit 1; }

read -rsp "seed_pw (demo tester/crowd login password) — ENTER to generate: " PW; echo
[ -n "$PW" ] || PW="$(openssl rand -hex 12)"

umask 077
{
  echo "---"
  echo "# Generated by set-seed-secrets.sh — GHCR token + bot-claim reused from vault-chat.yml."
  echo "seed_ghcr_token: \"$GH\""
  echo "seed_chat_bot_claim_secret: \"$BC\""
  echo "seed_pw: \"$PW\""
} > "$VAULT"
unset GH BC PW

ansible-vault encrypt --vault-password-file "$PWF" "$VAULT"
git -C "$ROOT" add -f "$VAULT"
cat <<EOF

── vault-seed.yml written, encrypted (bot-claim matches chat), git-staged ──────
Commit + push it (ciphertext, safe on the remotes):
    git -C "$ROOT" commit -m "seed: add encrypted vault" && git -C "$ROOT" push
EOF
