#!/usr/bin/env bash
# Interactively assemble ansible/group_vars/account/vault.yml — the encrypted
# secrets for the account profile: the GHCR read:packages token and the two
# PRIVATE minting keys (ed25519 voucher seed + blind-RSA anon-issuer key).
#
# Run this on a TRUSTED machine. Secrets are typed with hidden input or
# generated locally; nothing is echoed. The file is ansible-vault ENCRYPTED
# before it touches disk-at-rest git; the plaintext is shredded.
#
# Needs: openssl, ansible-vault, python3. The chat host's PUBLIC counterparts
# (CHAT_VOUCHER_PUBKEY / anon pub PEM) are printed at the end — copy them there.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VAULT="$ROOT/ansible/group_vars/account/vault.yml"

for bin in openssl ansible-vault python3; do
  command -v "$bin" >/dev/null 2>&1 || { echo "$bin is required." >&2; exit 1; }
done

if [ -e "$VAULT" ]; then
  read -rp "vault.yml already exists — overwrite? [y/N] " ans
  [ "$ans" = y ] || { echo "Aborted."; exit 1; }
fi

# --- 1. GHCR token (read:packages) --------------------------------------------
read -rsp "GHCR read:packages token (github PAT, hidden): " GHCR_TOKEN; echo
[ -n "$GHCR_TOKEN" ] || { echo "Empty token — aborting." >&2; exit 1; }

# --- 2. Voucher seed (ed25519) ------------------------------------------------
# 32 random bytes as 64 hex. voucher_pubkey = the ed25519 public key of the seed
# (matches wire.voucher_pubkey: SigningKey(seed).verify_key.encode().hex()).
read -rsp "Voucher seed (64 hex) — ENTER to generate: " VOUCHER_SEED; echo
[ -n "$VOUCHER_SEED" ] || VOUCHER_SEED="$(openssl rand -hex 32)"
VOUCHER_PUB="$(python3 - "$VOUCHER_SEED" <<'PY'
import sys
seed = bytes.fromhex(sys.argv[1])
try:
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    from cryptography.hazmat.primitives import serialization
    pk = Ed25519PrivateKey.from_private_bytes(seed).public_key()
    print(pk.public_bytes(serialization.Encoding.Raw,
                          serialization.PublicFormat.Raw).hex())
except ImportError:
    try:
        import nacl.signing
        print(nacl.signing.SigningKey(seed).verify_key.encode().hex())
    except ImportError:
        print("UNAVAILABLE")
PY
)"

# --- 3. Anon-issuer key (blind-RSA private) -----------------------------------
read -rp "Anon-issuer key — [g]enerate fresh RSA-2048, or [p]aste existing PEM? [G/p] " ANON_MODE
if [ "${ANON_MODE:-g}" = p ] || [ "${ANON_MODE:-g}" = P ]; then
  echo "Paste the full private-key PEM, then Ctrl-D:"
  ANON_PRIV="$(cat)"
  ANON_PUB="$(printf '%s\n' "$ANON_PRIV" | openssl rsa -pubout 2>/dev/null)"
else
  ANON_PRIV="$(openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 2>/dev/null)"
  ANON_PUB="$(printf '%s\n' "$ANON_PRIV" | openssl rsa -pubout 2>/dev/null)"
fi
[ -n "$ANON_PRIV" ] || { echo "Empty anon key — aborting." >&2; exit 1; }

# --- write plaintext, then encrypt in place -----------------------------------
umask 077
{
  echo "---"
  echo "# Generated by set-account-secrets.sh — ansible-vault encrypted."
  echo "account_ghcr_token: \"$GHCR_TOKEN\""
  echo "account_voucher_seed: \"$VOUCHER_SEED\""
  echo "account_anon_issuer_key: |"
  printf '%s\n' "$ANON_PRIV" | sed 's/^/  /'
} > "$VAULT"
unset GHCR_TOKEN VOUCHER_SEED ANON_PRIV

echo
echo "Encrypting $VAULT — you'll be prompted for a vault password"
echo "(remember it; the same one is needed at apply time via ANSIBLE_VAULT_PASSWORD_FILE)."
ansible-vault encrypt "$VAULT"
git -C "$ROOT" add -f "$VAULT"

cat <<EOF

── vault.yml written, encrypted, and git-staged (add -f) ───────────────────────
Commit + push it (it is ciphertext, safe on the remotes):
    git -C "$ROOT" commit -m "account: add encrypted vault" && git -C "$ROOT" push

── Give these PUBLIC halves to the CHAT host (never the privates above) ────────
CHAT_VOUCHER_PUBKEY = ${VOUCHER_PUB}
CHAT_ANON_ISSUER_PUB (PEM):
${ANON_PUB}
EOF
[ "$VOUCHER_PUB" = UNAVAILABLE ] && echo \
  "NOTE: install python 'cryptography' (pip install cryptography) and re-derive the voucher pubkey, or run the accounts-repo command from DEPLOY.md."
