---
galaxy_info:
  role_name: greasewood
  author: cschlick
  description: Install and keep greasewood up to date from GitLab
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
